### ISSUE TITLE
PDF generated name

### ISSUE THREAD

**Issue by loicdelecroix** [cglacet/attestations#1]
Hello !
First of all, thanks for your app, I use it on my domotic server to automaticly generate my attestation every time I leave :smile: 

I checked the code, and saw there was a function name _pdfName_ which is supposed to named the PDF based on name, lastName & time of generation.

However, every time I want to save the PDF on my phone (or computer), the name generated is **get.pdf**

Is it because your app on Heroku is not up-to-date ?

**Comment by cglacet** [comment]
Hey! 

Thanks for you message, your use case is so fun I haven't even though that would be possible :)

I've noticed that too, its not because of the version hosted on Heroku, its because of [this line](url). The returned object is described here: [send](https://serverjs.io/documentation/reply/#send-), [type](https://serverjs.io/documentation/reply/#type-). Here is the problematic part of the code:

```js
async function downloadPDF(profile, reasons){
    const pdf = await certificatePDF(profile, reasons)
    return type('application/pdf').send(new Buffer(pdf));
}
```

I looked for a solution but that's the very first time I use this library so I'm not too sure what's the best option. I think it's based on [express.js](https://expressjs.com/) so maybe the answer is not within the library itself. 

The name simply comes from the URL route `/get?`, so if I change the URL route that would allow to rename the output, but it would still be a static name. I would like to use [the `pdfName ` function](https://github.com/cglacet/attestations/blob/16cb2d6ef4e9830374bdb72a4a5ca3d4340863b5/src/certificates.js#L38-L42) to rename the PDF dynamically. 

If you wonder why `'datesortie'` and `'heuresortie'` are in french where all other identifiers are in english, well, [I have no idea](https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/blob/0ab3aad98c8e1dd589dfffc9099563f271847a42/src/js/pdf-util.js#L31-L32).

**Comment by cglacet** [comment]
It should be working now, let me know if it seems fine to you ;).

**Comment by loicdelecroix** [comment]
So it was about a header to send :)
That's great for me, thank you :smiley:

**Comment by cglacet** [comment]
Yes apparently, I would never have guessed. I learned something today 😄.
